- fix neutrino rcS Path.

diff --git a/root/release/rcS_neutrino_hd60 b/root/release/rcS_neutrino_hd60
--- a/root/release/rcS_neutrino_hd60
+++ b/root/release/rcS_neutrino_hd60
@@ -76,33 +76,32 @@ killall -9 showiframe
 
 until false
 do
-    echo "starting GUI ->"
-    chmod 755 /usr/bin/neutrino
-    if [ -e /tmp/neutrino ]; then
-      chmod 755 /tmp/neutrino
-      /tmp/neutrino
-    else
-      /usr/bin/neutrino -v 0
-    fi
-    rtv=$?
-    echo "GUI ended <- RTV: " $rtv
-    case "$rtv" in
-      0) echo "0"
-        echo "SHUTDOWN"
-      init 0;;
-      1) echo "1"
-        echo "REBOOT"
-        echo "      *-*       " > /dev/dbox/oled0
-      init 6;;
-      3) echo "3"
-        echo "RESTART"
-        echo "    RESTART     " > /dev/dbox/oled0
-      sync;;
-      *) echo "*"
-        echo -e "\033[01;31mERROR: $rtv\033[00m"
-        echo "    *ERROR*     " > /dev/dbox/oled0
-      init 6;;
-    esac
+    	echo "[rcS] starting neutrino GUI ->"
+	/usr/local/bin/neutrino
+	rtv=$?
+	echo "GUI ended <- RTV: " $rtv
+	case "$rtv" in
+		0) echo "$rtv"
+			echo "RESTART"
+			echo "RESTART" > /dev/dbox/oled0
+			sync
+			;;
+		1) echo "$rtv"
+			echo "SHUTDOWN"
+			echo "SHUTDOWN" > /dev/dbox/oled0
+			init 0
+			;;
+		3) echo "$rtv"
+			echo "REBOOT"
+			echo "RBOOT" > /dev/dbox/oled0
+			init 6
+			;;
+		*) echo "*"
+			echo -e "\033[01;31mERROR: $rtv\033[00m"
+			echo "ERROR: $rtv" > /dev/dbox/oled0
+			init 6
+			;;
+	esac
 done
 echo "      *-*       " > /dev/dbox/oled0
 
